name: mem_value
description: Type-safe persistent storage wrapper with automatic serialization for Flutter.
version: 0.2.1
repository: "https://www.github.com/kld/mem_value"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
